[workspace]
authors = ["Thomas Ip <thomas@ipthomas.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "max-gpt-2"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
modular = ">=25.7.0.dev2025092905,<26"
